name = "lukairo-engine"
<<<<<<< Updated upstream
compatibility_date = "2025-01-01"

workers_dev = true
=======
main = "workers/app.ts"
compatibility_date = "2024-12-01"

[vars]
VALUE_FROM_CLOUDFLARE = "lukairo-edge"
>>>>>>> Stashed changes
